### ISSUE TITLE
[CoderSchool Android] Final Project - User stories and Wireframes are ready for review

### ISSUE THREAD

**Issue by yasuosm** [CoderShool-Android-2016-CatWoman/final-project-life-todo#1]
Our application's user stories and wireframes are ready. Please review. /cc @coderschoolreview

**Comment by hoanle** [comment]
@yasuosm @huongvu 
- Some classes are not in used ? (LoginActivity)
- Many empty classes? (AddTextFragment, AddPhotoFragment...)
- Some part is not really necessary if you don't use it. For exampleviewPager.addOnPageChangeListener in HomeActivity does not implement anything
- Comparing String should be done by using equals function, not item.getItemStatus() == "Done"
- If you use Butterknife, should use it consistently, HomeActivity still uses findViewById

**Comment by yasuosm** [comment]
Many thanks @hoanle for your review 😄 

Some notes from my side:
- viewPager.addOnPageChangeListener is used for animating Fab, implemented in onPageSelected method (other empty methods are required to implement by parent)
- HomeActivity has been updated to use Butterknife.

@huongvu: Thanks to follow up other issues 😄

**Comment by huongvu** [comment]
@yasuosm,

Update AddTextFragment, Comparing String, Add/Edit/Delete Item in SQLite DB

**Comment by hoanle** [comment]
@yasuosm @huongvu 

Report bug:
- Can add empty item just by clicking on "Add Ya Book" and save
- After click to finish an item, press back, then go into item list again ==> the last item is in unfinish state 
- Remove item can cause crash

```

java.lang.IndexOutOfBoundsException: Invalid index 1, size is 1
                                                                           at java.util.ArrayList.throwIndexOutOfBoundsException(ArrayList.java:255)
                                                                           at java.util.ArrayList.set(ArrayList.java:481)
                                                                           at com.catwoman.lifetodo.activities.TodoItemsActivity$3.EditItem(TodoItemsActivity.java:117)
                                                                           at com.catwoman.lifetodo.adapters.TodoItemsAdapter$1.onClick(TodoItemsAdapter.java:121)
```
- Click on any category will lead to the same page, with the same list

Suggestion
- You could remove the setting button (top right) by delete all item in the menu file
- Although you use io.realm to manage database, which is easy way and nice, but i do think you should separate all the database-relating code into one class. For example

`RealmResults<TodoItem> results = realm.where(TodoItem.class).findAllSorted("id", Sort.ASCENDING);`

should be moved out of TodoItemsActivity
- Since ButterKnife is integrated, don't use findViewById anymore
